version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    env_file: 
      - ./docker/client/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/client:/client:z
    stdin_open: true
    tty: true
