version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    env_file: 
      - ./docker/client/.env.development
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/client:/client:z
    stdin_open: true
    tty: true
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file: 
      - ./docker/server/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/server:/server:z
    stdin_open: true
    tty: true
  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    env_file: 
      - ./docker/mongo/.env.development
    restart: on-failure
    volumes:
      - ${PWD}/tmp/mongo:/data/db
  